### ISSUE TITLE
Implement server & worker init & final scripts

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#248]
_From @asparke2 on May 11, 2017 16:5_

Necessary for ResStock and ComStock

_Copied from original issue: NREL/OpenStudio#2608_

**Comment by rHorsey** [comment]
Worker is implemented and tested. Server will get implemented next week.

**Comment by rHorsey** [comment]
@shorowit found a lovely bug with *.sh files coming from windows. This has been addressed using dos2unix in https://github.com/NREL/OpenStudio-server/commit/7dc6836f02ba8a450f0438d410091efa4a0c97e1

**Comment by rHorsey** [comment]
Worker looks to be mostly stable. There are some paradoxes in when to apply worker finalization in the workflow, but otherwise the implementation appears solid.

**Comment by rHorsey** [comment]
Worker is being merged in. Sever remains to be done.

**Comment by rHorsey** [comment]
_From @asparke2 on August 10, 2017 1:12_

Sweet!

**Comment by rHorsey** [comment]
Defining server finalization as major, and server initialization as minor.

**Comment by anyaelena** [comment]
Per Pivotal, it looks like this should be assigned to me.  It would be helpful if I could get a concrete example of what we are trying to do. I discussed with @nllong running code on only the server docker container as part of the deployment process - presumably this is "initialization".  Is "finalization" a final stage of setup or part of the destroy process for the server container?  And are we only talking about Docker here?

**Comment by anyaelena** [comment]
@nllong @rHorsey Notes from our call:

Analysis finalization should be triggered from web_background but run on web_1, which has superior resources and memory management.

Consider triggering this via a HTTP action for the analysis.  Since this may take longer than a standard HTTP request and we don't want it to time out, we will still need the actual script(s) to run in the background on web_1, meaning that we need to use Resque on web_1.  

So:
1. Analysis completes
2. background task calls http method on web
3. web adds "run_finalization_scripts" to queue for background tasks that run on web.

Now we can all think what's wrong with this...

**Comment by anyaelena** [comment]
I guess there is no reason for the http call.  

1. Analysis completes
2. web_background puts run_finalization_scripts in queue
3. web_1 runs  "run_finalization_scripts" in background
