### ISSUE TITLE
cancel run does not work anymore

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-server#437]
run any of the SEB examples and try and cancel the run.

**Comment by nllong** [comment]
PAT: 2.7.1
OpenStudio Server: 2.7.1

The status gets set to Complete almost immediately, but the set of simulations that are queued are left in the queue to finish. Do you expect that all the queued simulations disappear upon clicking "cancel"?  

![image](https://user-images.githubusercontent.com/1907354/49903949-ee4bf300-fe25-11e8-8e34-9c72257a3bb5.png)

**Comment by anyaelena** [comment]
working on two things:

1. Reviewing implications of introducing "pending cancellation" and "cancelled" statuses for analyses.  
1. Deletion of all queued simulations when analysis in cancelled.  Note that these do  clear out quickly by failing with a `undefined method `status=' for nil:NilClass` error once the analysis has been cancelled.  Not ideal but at least the workers do free up.

**Comment by anyaelena** [comment]
regarding queued datapoints not being removed, [this](https://github.com/NREL/OpenStudio-server/blob/develop/server/app/models/data_point.rb#L163) must not be working as expected.

**Comment by anyaelena** [comment]
ok.  Running the "SEB_calibration_RepeatRun_2013" sample project from PAT against a locally deployed instance, canceling the run from PAT has no effect.  The RunAnalysis Resque job remains active and datapoints keep running and completing.

**Comment by anyaelena** [comment]
I'm fairly sure that the issue is this:

1) we only clean up "queued" datapoints when the analysis is canceled: https://github.com/NREL/OpenStudio-server/blob/develop/server/app/models/analysis.rb#L172
2) the status is set to queued in the [initialize block](https://github.com/NREL/OpenStudio-server/blob/develop/server/app/jobs/dj_jobs/run_simulate_data_point.rb#L49) for the delayed jobs job, 
3) which is called [immediately before perform](https://github.com/NREL/OpenStudio-server/blob/develop/server/app/jobs/resque_jobs/run_simulate_data_point.rb#L43) when we are using resque for queue management
